import { Metadata } from 'next'
import Link from 'next/link'
import React from 'react'
export const metadata: Metadata = {
    title: 'Manager',
    description: 'Generated by create next app',
}
export default function ManagerLayout({ children }: { children: React.ReactNode }) {
    return <> {children}</>
}
